# Generated by Django 3.2.5 on 2021-07-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('fathername', models.CharField(max_length=10)),
                ('mothername', models.CharField(max_length=10)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(max_length=6)),
                ('about', models.CharField(max_length=20)),
            ],
        ),
    ]
