# Generated by Django 3.2.5 on 2021-07-25 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdetails',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 25, 14, 52, 0, 657966, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
